name: couchclient
version: 0.3.0+7
author: Henri Chen <henrichen@rikulo.org>
description: |
  A Couchbase client library written in Dart language.
homepage: http://rikulo.org
dependencies:
  crypto: any
  logging: any
  memcached_client: any
  unittest: any
